joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/utils/parallel.py", line 127, in __call__
    return self.function(*args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/pipeline.py", line 957, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/base.py", line 919, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/preprocessing/_function_transformer.py", line 240, in transform
    return self._transform(X, func=self.func, kw_args=self.kw_args)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/preprocessing/_function_transformer.py", line 312, in _transform
    return func(X, **(kw_args if kw_args else {}))
  File "mlp_other.py", line 73, in features
    result = np.hstack((stop_words_features, empath_features))
  File "<__array_function__ internals>", line 5, in hstack
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mlp_other.py", line 118, in <module>
    model.fit(X_train, y_train)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/imblearn/pipeline.py", line 322, in fit
    Xt, yt = self._fit(X, y, routed_params)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/imblearn/pipeline.py", line 248, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/imblearn/pipeline.py", line 1097, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/pipeline.py", line 1269, in fit_transform
    results = self._parallel_func(X, y, fit_params, _fit_transform_one)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/pipeline.py", line 1291, in _parallel_func
    return Parallel(n_jobs=self.n_jobs)(
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/sklearn/utils/parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
  File "/home/users/nus/e0878495/scratch/lib/conda/envs/CS4248/lib/python3.8/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			Resource Usage on 2024-04-18 12:46:56.657248:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	JobId: 6790302.pbs101
	Project: 11003862
	Exit Status: 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	NCPUs: Requested(128), Used(128)
	CPU Time Used: 00:06:38
	Memory: Requested(256gb), Used(7496460kb)
	Vmem Used: 42264548kb
	Walltime: Requested(04:00:00), Used(00:06:00)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	Execution Nodes Used: (x1003c5s5b1n0:ncpus=128:mem=268435456kb)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	No GPU-related information available for this job.
